version: "3"
services:
  auth:
    build: ./auth-api
    environment:
      AUTH_ADDRESS: "auth"
  users:
    build: ./users-api
    ports:
      - "8080:8080"
  tasks:
    build: ./tasks-api
    ports:
      - "8000:8000"
    environment:
      TASKS_FOLDER: "tasks"
      AUTH_ADDRESS: "auth"
