apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizon
spec:
  selector:
    matchLabels:
      app: horizon
  template:
    metadata:
      labels:
        app: horizon
    spec:
      containers:
        - name: horizon
          image: mo7zayed/larakube:latest
          imagePullPolicy: Always
          command:
            - php
          args:
            - -d
            - memory_limit=-1
            - artisan
            - horizon
          resources:
            limits:
              memory: "1500Mi"
              cpu: "500m"
