apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
spec:
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
        - name: http
          image: mo7zayed/larakube:latest
          imagePullPolicy: Always
          command:
            - php
          args:
            - -d
            - memory_limit=-1
            - artisan
            - serve
            - --host=0.0.0.0
            - --port=80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 10
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
