apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-api
spec:
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api
    spec:
      containers:
      - name: tasks-api
        image: mo7zayed/tasks-api:latest
        env:
          - name: 'AUTH_URL'
            value: 'auth-service.default' # service-name.namespace-name
          - name: 'TASKS_FOLDER'
            value: 'tasks'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"