apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: mo7zayed/users-api:latest
        env:
          - name: 'AUTH_URL'
            value: 'auth-service.default' # service-name.namespace-name
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"